name: git push into dev repo to deploy to vercel

on:
  push:
    branches: [feat/github-action-setting]

jobs:
  build:
    permissions: 
      contents: read
      pages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        id: push_director
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'prkgnt'
          destination-repository-name: 'tech-swipe-front-deploy'
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          target-branch: develop
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
